"""Step 2.3 — measure the chunk set Step 2.2 produces, before Step 2.4
persists it and Phase 4 embeds it."""

from __future__ import annotations

import sys
import time
from pathlib import Path

from taxverity.chunking.pipeline import build_from_corpus, read_corpus_version
from taxverity.chunking.stats import (
    CONTEXT_TOKENS,
    LARGE_CHUNK_TOKENS,
    SAFETY_FACTOR,
    SMALL_CHUNK_TOKENS,
    ChunkStatistics,
    Distribution,
    summarise,
)
from taxverity.config import Settings
from taxverity.observability import configure_logging, get_logger

logger = get_logger(__name__)

REPORT = Path("reports") / "chunk_stats.md"


def distribution_row(name: str, dist: Distribution) -> str:
    return (
        f"| {name} | {dist.minimum} | {dist.p50} | {dist.p90} | "
        f"{dist.p95} | {dist.p99} | {dist.maximum} |"
    )


def render(stats: ChunkStatistics, elapsed: float) -> str:
    matched = stats.chunks - stats.chunks_without_terms
    lines = [
        "# Chunk statistics — Income-tax Act, 2025",
        "",
        "Auto-generated by `scripts/chunk_stats.py` (Step 2.3) over the chunk",
        "set Step 2.2 builds from the parsed section and Schedule trees. No",
        "chunk artifact is read — the whole pipeline is re-run — so these",
        "figures always describe the current parser.",
        "",
        "## Shape",
        "",
        "| Measure | Value |",
        "|---|---|",
        f"| Chunks | {stats.chunks} |",
        f"| Roots (537 sections + 16 Schedules) | {stats.roots} |",
        f"| Build time | {elapsed:.1f}s |",
        "",
        "| Node type | Chunks |",
        "|---|---|",
        *[f"| {node_type.value} | {count} |" for node_type, count in stats.by_type],
        "",
        "| Citation depth | Chunks |",
        "|---|---|",
        *[f"| {depth + 1} | {count} |" for depth, count in stats.by_depth],
        "",
        "## Size distribution",
        "",
        "Characters are over `chunk.text`, which is what the Step 2.4 store",
        "will hold. Tokens are over `chunk.embed_text()` — the breadcrumb",
        "travels to the embedding model with the text, so the context check",
        "has to include it. Percentiles are nearest-rank, so every figure",
        "below is a value some real chunk actually has.",
        "",
        "| Measure | min | p50 | p90 | p95 | p99 | max |",
        "|---|---|---|---|---|---|---|",
        distribution_row("Characters", stats.characters),
        distribution_row("Estimated tokens", stats.tokens),
        distribution_row("Defined terms", stats.terms_per_chunk),
        distribution_row("Outgoing refs", stats.refs_per_chunk),
        "",
        "## Does anything overflow the embedding context?",
        "",
        "No. The token figures above are a **word/punctuation proxy**, not a",
        "real subword count — no embedding model is chosen until the Phase 4.7",
        "bake-off, and each candidate has its own vocabulary, so a real count",
        "taken now would be a count of the wrong model. The proxy is a floor",
        "(BPE splits long words further, never fewer), and it measures roughly",
        "4.7 characters per token over this corpus, close to the usual ~4",
        "chars/token rule of thumb.",
        "",
        f"The check therefore multiplies the proxy by a pessimistic {SAFETY_FACTOR}x",
        "before comparing it against the 32K context both Phase 4 candidates",
        "carry:",
        "",
        "| Measure | Value |",
        "|---|---|",
        f"| Context window (jina-v5-small, Qwen3-0.6B) | {CONTEXT_TOKENS} |",
        f"| Largest chunk, proxy | {stats.tokens.maximum} |",
        f"| Largest chunk, proxy x{SAFETY_FACTOR} | {stats.tokens.maximum * SAFETY_FACTOR} |",
        f"| Chunks over the context, proxy | {stats.over_context} |",
        f"| Chunks over the context, proxy x{SAFETY_FACTOR} | {stats.over_context_with_safety} |",
        "",
        "`Chunk.token_count` is deliberately left `None`, a stated deviation",
        "from the plan's Step 2.1 note 5. A proxy persisted into the Step 2.4",
        "store is a number Phase 4 would read as authoritative — the same",
        "drift `citation_label` and `Settings.interim_dir` are structured to",
        "avoid. Phase 4 fills it with the chosen model's own tokenizer, once",
        "there is a chosen model. See ADR-057.",
        "",
        "## The large chunks, named and explained",
        "",
        f"{len(stats.large)} chunks exceed {LARGE_CHUNK_TOKENS} estimated tokens. This is",
        "not a violated cap — ADR-055 makes a chunk carry its whole subtree, so",
        "a long section is *expected* to produce one long chunk, and the",
        "precise retrieval unit is its children. The success criterion for this",
        "step is that each one is looked at and understood, which is what this",
        "table is:",
        "",
        "| Citation | Type | Est. tokens | Characters | Why it is this large |",
        "|---|---|---|---|---|",
        *[
            f"| {o.node_path} | {o.node_type.value} | {o.tokens} | "
            f"{o.characters} | {o.reason} |"
            for o in stats.large
        ],
        "",
        "The non-root entries are the ones worth noting: they are single",
        "sub-sections long enough to dominate their own sections. They still",
        "split normally below, so a query matching one clause inside them",
        "retrieves that clause — the large chunk is the parent context, not the",
        "only way in.",
        "",
        "## The small chunks",
        "",
        "| Measure | Value |",
        "|---|---|",
        f"| Chunks under {SMALL_CHUNK_TOKENS} estimated tokens | {stats.small} |",
        f"| Chunks that are only an omission mark | {stats.omitted_only} |",
        "",
        "Neither group is removed. A chunk like `Schedule XII(A8)` is",
        "genuinely the entire text at that citation, and an omitted clause such",
        "as `206(1)(m)` is the Act's own record that something was repealed",
        "there — a user asking about it deserves that answer rather than",
        "silence. Both are, however, near-useless as *retrieved evidence* on",
        "their own, and Phase 3's gold set should expect them to be reached",
        "through their parent rather than labelled directly.",
        "",
        "## `defined_terms` — the field Phase 5 will lean on",
        "",
        "| Measure | Value |",
        "|---|---|",
        f"| Section 2 glossary terms | {stats.glossary_terms} |",
        f"| Chunks matching at least one | {matched} |",
        f"| Chunks matching none | {stats.chunks_without_terms} |",
        f"| Terms per chunk, p50 | {stats.terms_per_chunk.p50} |",
        f"| Terms per chunk, max | {stats.terms_per_chunk.maximum} |",
        "",
        "**This field is not yet usable as a retrieval signal, and that is the",
        "finding of this step.** Matching is a plain case-insensitive substring",
        "test (Step 2.2), so the most frequent defined terms are simply the",
        "most frequent words:",
        "",
        "| Term | Chunks |",
        "|---|---|",
        *[f"| {term} | {count} |" for term, count in stats.term_frequency[:15]],
        "",
        "A term matching a third of the corpus carries no information. Phase",
        "5's statutory-term bridge needs the inverse direction — a lay phrase",
        "mapped to the statutory term whose *definition* it should pull in —",
        "and it should treat this field as a candidate set to filter, never as",
        "a ranking signal. Word-boundary matching and a stop-term list are the",
        "obvious first corrections; both belong to Phase 5, which has an eval",
        "set to measure them against. Nothing is changed here on speculation.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    configure_logging()
    settings = Settings()
    source = settings.interim_dir / "pages.jsonl"
    if not source.exists():
        logger.error("missing %s — run scripts/extract_corpus.py first", source)
        return 1

    started = time.perf_counter()
    corpus_version = read_corpus_version(settings.interim_dir / "corpus_manifest.json")
    build = build_from_corpus(source, settings.resolve_corpus_pdf(), corpus_version)
    stats = summarise(
        build.chunks,
        untrusted=build.untrusted,
        glossary_size=len(build.crossrefs.glossary),
    )
    elapsed = time.perf_counter() - started

    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(render(stats, elapsed), encoding="utf-8", newline="\n")

    print(f"chunks       {stats.chunks} ({stats.roots} roots)")
    print(
        f"characters   p50 {stats.characters.p50}  p95 {stats.characters.p95}"
        f"  max {stats.characters.maximum}"
    )
    print(
        f"est. tokens  p50 {stats.tokens.p50}  p95 {stats.tokens.p95}"
        f"  max {stats.tokens.maximum}"
    )
    print(
        f"context      {CONTEXT_TOKENS}, over with {SAFETY_FACTOR}x safety:"
        f" {stats.over_context_with_safety}"
    )
    print(f"large        {len(stats.large)} over {LARGE_CHUNK_TOKENS} tokens")
    print(
        f"small        {stats.small} under {SMALL_CHUNK_TOKENS} tokens"
        f" ({stats.omitted_only} omission-only)"
    )
    print(
        f"terms        {stats.chunks - stats.chunks_without_terms} chunks match at"
        f" least one of {stats.glossary_terms}"
    )
    print(f"report       {REPORT} ({elapsed:.1f}s)")
    return 0 if stats.fits_context else 1


if __name__ == "__main__":
    sys.exit(main())
