"""Step 3.6 — measure the lexical baseline against the Step 3.1 gold set.

Writes `evals/reports/<corpus_version>/baseline_bm25.json` (the machine record
every later phase compares against) and `reports/retrieval_baseline.md` (the
human one).
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path

from taxverity.chunking.store import load_chunks
from taxverity.config import Settings
from taxverity.evals.baseline import (
    K_VALUES,
    PRIMARY_K,
    BaselineReport,
    RetrieverBaseline,
    measure,
)
from taxverity.evals.gold import GOLD_V2_FILENAME, QuerySlice, load_gold_set
from taxverity.evals.metrics import CitationIndex, CreditMode, RunReport
from taxverity.observability import configure_logging, get_logger
from taxverity.retrieval.bm25 import BM25Retriever
from taxverity.retrieval.citations import CitationRetriever, ShortcutRetriever

logger = get_logger(__name__)

REPORT = Path("reports") / "retrieval_baseline.md"
ARTIFACT = "baseline_bm25.json"

BM25 = "bm25"
SHORTCUT = "bm25+citation_shortcut"


def scores_row(name: str, report: RunReport, mode: CreditMode) -> str:
    scores = report.overall[mode]
    return (
        f"| {name} | {mode.value} | {scores.recall:.3f} | "
        f"{scores.mrr:.3f} | {scores.ndcg:.3f} |"
    )


def slice_rows(baseline: RetrieverBaseline, mode: CreditMode) -> list[str]:
    report = baseline.primary
    return [
        f"| {member.value} | {mode.value} | {report.per_slice[member][mode].recall:.3f} "
        f"| {report.per_slice[member][mode].mrr:.3f} "
        f"| {report.per_slice[member][mode].ndcg:.3f} |"
        for member in QuerySlice
        if member is not QuerySlice.NEGATIVE
    ]


def render(report: BaselineReport, elapsed: float) -> str:
    lines = [
        "# Retrieval baseline — Income-tax Act, 2025",
        "",
        "Auto-generated by `scripts/measure_retrieval.py` (Step 3.6) over the",
        "Step 2.4 chunk store and the Step 3.1 gold set. Every later retrieval",
        "component is judged against these numbers.",
        "",
        "| Measure | Value |",
        "|---|---|",
        f"| corpus_version | `{report.corpus_version[:16]}…` |",
        f"| Chunks | {report.chunk_count} |",
        f"| Gold queries | {report.gold_count} |",
        f"| Primary k | {report.primary_k} |",
        f"| Run time | {elapsed:.1f}s |",
        "",
        "Every score is reported twice (ADR-060). **strict** credits only the",
        "labelled unit; **lenient** also credits an ancestor, because ADR-055",
        "gives a chunk its whole subtree — a retriever returning `22` for a",
        "`22(2)` question is imprecise, not wrong.",
        "",
        "**Known consequence of Step 1.10, not a regression.** Narrowing the",
        "trust rule to `duplicate_path` split 19 roots into their real",
        "sub-structure (7,561 -> 8,351 chunks), and bm25 alone went",
        "0.445 / 0.469 to 0.438 / 0.461. The whole of that fall is **one query**,",
        "q064, losing half credit — 0.5 / 64 = 0.008, which is the entire delta.",
        "",
        "What happened there is worth reading before treating it as a loss.",
        "q064 asks whether an unexplained cash credit is taxed at the normal slab",
        "rate, and is labelled `102(1)` / `195(1)`. The newly reachable definition",
        "`2(70)` — *\"maximum marginal rate\"*, which is precisely the rate such a",
        "credit is charged at — now takes rank 1 and pushes `102(1)` to rank 11.",
        "The retriever surfaced a provision that is on point and unlabelled, and",
        "was scored down for it. That is a gold-set limitation, not a retrieval",
        "one.",
        "",
        "Gold q052 (`2`) and q067 (`393`) score 0 in both modes — but they did so",
        "**before this change too**, so they are unaffected by it. They remain",
        "exposed to ADR-060 crediting no descendant, and are the clearest",
        "candidates for the re-labelling pass. Re-labelling is deliberately kept",
        "separate: editing the gold set here would move the ruler and the",
        "measured thing in the same change.",
        "",
    ]

    for baseline in report.retrievers:
        lines += [
            f"## {baseline.name}",
            "",
            f"Overall, over {len(baseline.outcomes)} answerable queries:",
            "",
            "| k | mode | recall | MRR | nDCG |",
            "|---|---|---|---|---|",
        ]
        for k in report.k_values:
            for mode in CreditMode:
                lines.append(scores_row(str(k), baseline.reports[k], mode))
        lines += [
            "",
            f"Per slice, at k={report.primary_k}:",
            "",
            "| slice | mode | recall | MRR | nDCG |",
            "|---|---|---|---|---|",
        ]
        for mode in CreditMode:
            lines += slice_rows(baseline, mode)

        lines += [
            "",
            f"### Failures at k={report.primary_k}",
            "",
            "A query is a failure only when a label is missed *leniently* —",
            "strict imprecision is reported in the tables above, not here.",
            "",
        ]
        if not baseline.failures:
            lines.append("None.")
        else:
            lines += [
                "| query | slice | required | missed | first hit | question |",
                "|---|---|---|---|---|---|",
                *[
                    f"| {o.query_id} | {o.slice.value} | {', '.join(o.required)} | "
                    f"{', '.join(o.missed) or '—'} | {o.first_hit_rank or '—'} | "
                    f"{o.question} |"
                    for o in baseline.failures
                ],
            ]

        lines += [
            "",
            "### Imprecise but not wrong",
            "",
            "Answered leniently, missed strictly: the labelled unit was reached",
            "only through an ancestor chunk.",
            "",
        ]
        imprecise = [
            o
            for o in baseline.outcomes
            if o.lenient_recall > o.strict_recall
        ]
        if not imprecise:
            lines.append("None.")
        else:
            lines += [
                "| query | required | strict | lenient | retrieved (top 3) |",
                "|---|---|---|---|---|",
                *[
                    f"| {o.query_id} | {', '.join(o.required)} | {o.strict_recall:.2f} "
                    f"| {o.lenient_recall:.2f} | {', '.join(o.retrieved[:3])} |"
                    for o in imprecise
                ],
            ]

        answerable_scores = [
            o.top_score for o in baseline.outcomes if o.top_score is not None
        ]
        negative_scores = [
            n.top_score for n in baseline.negatives if n.top_score is not None
        ]
        lines += [
            "",
            "### Negative separation",
            "",
            "Negatives carry no label, so recall, MRR and nDCG are undefined for",
            "them (ADR-060). What they have is a top-1 score, and the gap",
            "between these and the answerable ones is the first evidence a",
            "Phase 12 threshold can be argued from rather than invented. A",
            "score is comparable only within one retriever (Step 3.3), so this",
            "table must be read one row-group at a time.",
            "",
        ]
        if baseline.ordinal_scores:
            lines += [
                "This retriever composes two rankings by **position** (Step",
                "3.5), so its scores record an order and measure nothing. No",
                "separation is reported; read the un-composed retriever above.",
                "",
            ]
        else:
            lines += [
                "| set | queries | min | median | max |",
                "|---|---|---|---|---|",
                distribution_row("answerable", answerable_scores),
                distribution_row("negative", negative_scores),
                "",
            ]
        lines += [
            "| query | top citation | question |",
            "|---|---|---|",
            *[
                f"| {n.query_id} | {n.top_citation or '—'} | {n.question} |"
                for n in baseline.negatives
            ],
            "",
        ]

    return "\n".join(lines) + "\n"


def distribution_row(name: str, values: list[float]) -> str:
    if not values:
        return f"| {name} | 0 | — | — | — |"
    ordered = sorted(values)
    middle = ordered[len(ordered) // 2]
    return (
        f"| {name} | {len(ordered)} | {ordered[0]:.2f} | "
        f"{middle:.2f} | {ordered[-1]:.2f} |"
    )


def main() -> int:
    configure_logging()
    settings = Settings()
    started = time.perf_counter()

    try:
        chunks, manifest = load_chunks(settings.interim_dir)
    except RuntimeError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    gold = load_gold_set(settings.evals_dir / "datasets" / GOLD_V2_FILENAME)
    index = CitationIndex(chunks)

    bm25 = BM25Retriever(chunks)
    shortcut = CitationRetriever(chunks)
    report = BaselineReport(
        corpus_version=manifest.corpus_version,
        chunk_count=len(chunks),
        gold_count=len(gold),
        k_values=K_VALUES,
        primary_k=PRIMARY_K,
        retrievers=(
            measure(BM25, bm25, gold, index),
            measure(
                SHORTCUT,
                ShortcutRetriever(shortcut, bm25),
                gold,
                index,
                ordinal_scores=True,
            ),
        ),
    )

    artifact_dir = settings.evals_dir / "reports" / manifest.corpus_version
    artifact_dir.mkdir(parents=True, exist_ok=True)
    artifact = artifact_dir / ARTIFACT
    with artifact.open("w", encoding="utf-8", newline="") as handle:
        handle.write(
            json.dumps(
                report.model_dump(mode="json"),
                sort_keys=True,
                ensure_ascii=False,
                separators=(",", ":"),
            )
        )
        handle.write("\n")

    elapsed = time.perf_counter() - started
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(render(report, elapsed), encoding="utf-8", newline="")

    for baseline in report.retrievers:
        overall = baseline.primary.overall
        print(
            f"{baseline.name}: strict recall@{PRIMARY_K} "
            f"{overall[CreditMode.STRICT].recall:.3f}, lenient "
            f"{overall[CreditMode.LENIENT].recall:.3f}, "
            f"{len(baseline.failures)} failures"
        )
    print(f"wrote {artifact}")
    print(f"wrote {REPORT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
