"""Step 5.3 — evidence delivery measured against the ranking it delivers from,
judged by the rule registered in `taxverity.evals.delivery` before this script
first ran (ADR-082).

Reads the cached gold-question vectors Step 5.2 wrote, so it bills no tokens.
Requires `TAXVERITY_JINA_API_KEY` all the same: the embedder's identity is
checked against the vector store.

Writes `evals/reports/<corpus_version>/evidence_delivery.json` and
`reports/evidence_delivery.md`.
"""

from __future__ import annotations

import json
import math
import sys
import time
from collections.abc import Sequence
from pathlib import Path

from pydantic import BaseModel, ConfigDict

from taxverity.chunking.pipeline import read_corpus_version
from taxverity.chunking.stats import estimate_tokens
from taxverity.chunking.store import load_chunks
from taxverity.config import MissingSettingError, Settings
from taxverity.embedding.jina_api import JinaAPIEmbedder
from taxverity.embedding.store import StaleVectorStoreError
from taxverity.evals.baseline import PRIMARY_K, measure
from taxverity.evals.delivery import judge_delivery
from taxverity.evals.gold import GOLD_V2_FILENAME, QuerySlice, load_gold_set
from taxverity.evals.ladder import Verdict
from taxverity.evals.metrics import CitationIndex, CreditMode, RunReport, score_run
from taxverity.evals.query_vectors import (
    QUERY_VECTORS_FILENAME,
    CachedQueryRetriever,
    load_query_vectors,
)
from taxverity.observability import configure_logging, get_logger
from taxverity.retrieval.bm25 import BM25Retriever
from taxverity.retrieval.citations import CitationRetriever, ShortcutRetriever
from taxverity.retrieval.dense import DenseRetrievalError, DenseRetriever
from taxverity.retrieval.evidence import (
    EVIDENCE_BUDGET,
    EVIDENCE_POOL,
    EvidencePack,
    EvidencePacker,
)
from taxverity.retrieval.fusion import FusionRetriever

logger = get_logger(__name__)

REPORT = Path("reports") / "evidence_delivery.md"
ARTIFACT = "evidence_delivery.json"
VECTORS_KEY = "jina-api"


class QueryDelivery(BaseModel):
    model_config = ConfigDict(frozen=True)

    query_id: str
    slice: QuerySlice
    question: str
    units: tuple[str, ...]
    tokens: int
    context_tokens: int
    skipped: tuple[str, ...]


class EvidenceReport(BaseModel):
    model_config = ConfigDict(frozen=True)

    corpus_version: str
    chunk_count: int
    gold_count: int
    budget: int
    pool: int
    ranked_k: int
    ranked: RunReport
    delivered: RunReport
    verdict: Verdict
    queries: tuple[QueryDelivery, ...]
    pack_ms: tuple[float, float]


def percentiles(samples: Sequence[float]) -> tuple[float, float]:
    ordered = sorted(samples)
    return ordered[len(ordered) // 2], ordered[math.ceil(0.95 * len(ordered)) - 1]


def context_tokens(pack: EvidencePack) -> int:
    return sum(estimate_tokens(line.text) for unit in pack.units for line in unit.context)


def lenient(report: RunReport) -> dict[str, float]:
    return {s.query_id: s.lenient.recall for s in report.scored}


def render(report: EvidenceReport, elapsed: float) -> str:
    answerable = [q for q in report.queries if q.slice is not QuerySlice.NEGATIVE]
    negatives = [q for q in report.queries if q.slice is QuerySlice.NEGATIVE]
    tokens = sorted(q.tokens for q in answerable)
    total = sum(q.tokens for q in report.queries)
    context = sum(q.context_tokens for q in report.queries)
    before, after = lenient(report.ranked), lenient(report.delivered)
    gains = [q for q in answerable if after[q.query_id] > before[q.query_id]]
    losses = [q for q in answerable if after[q.query_id] < before[q.query_id]]
    verdict = report.verdict
    lines = [
        "# Evidence delivery — Income-tax Act, 2025",
        "",
        "Auto-generated by `scripts/measure_evidence.py` (Step 5.3). The hybrid +",
        "shortcut ranking (ADR-081) read to the pool depth, deduplicated by ancestry,",
        "each hit prefixed by its ancestors' lead-in lines, packed within the budget",
        "(ADR-082). Token counts are the Step 2.3 proxy, about 1.145x short of real.",
        "",
        "| Measure | Value |",
        "|---|---|",
        f"| corpus_version | `{report.corpus_version[:16]}…` |",
        f"| Chunks | {report.chunk_count} |",
        f"| Gold queries | {report.gold_count} |",
        f"| Budget / pool | {report.budget} tokens / top {report.pool} |",
        f"| Pack time p50 / p95 | {report.pack_ms[0]:.2f} / {report.pack_ms[1]:.2f} ms |",
        f"| Run time | {elapsed:.1f}s |",
        "",
        "## The rule (registered before the run, ADR-082)",
        "",
        f"The delivered evidence must credit every label the ranking's top {report.ranked_k}",
        "credited: lenient recall must not fall, overall or on any slice. No rise is",
        "required.",
        "",
        f"**Verdict: {'ADOPTED' if verdict.adopted else 'REJECTED'}.**",
        "",
        *([f"- {reason}" for reason in verdict.reasons] or ["- every clause held"]),
        "",
        "## Coverage",
        "",
        "Lenient recall: the share of labels whose text the evidence carries.",
        "",
        f"| slice | ranking top {report.ranked_k} | delivered pack |",
        "|---|---|---|",
        f"| overall | {report.ranked.overall[CreditMode.LENIENT].recall:.3f} "
        f"| {report.delivered.overall[CreditMode.LENIENT].recall:.3f} |",
    ]
    for member, scores in report.ranked.per_slice.items():
        lines.append(
            f"| {member.value} | {scores[CreditMode.LENIENT].recall:.3f} "
            f"| {report.delivered.per_slice[member][CreditMode.LENIENT].recall:.3f} |"
        )
    lines += [
        "",
        "## Cost",
        "",
        "| Measure | Value |",
        "|---|---|",
        f"| Tokens per answerable pack, p50 / p95 / max | {tokens[len(tokens) // 2]} "
        f"/ {tokens[math.ceil(0.95 * len(tokens)) - 1]} / {tokens[-1]} |",
        f"| Units per answerable pack, mean | "
        f"{sum(len(q.units) for q in answerable) / len(answerable):.2f} |",
        f"| Share of delivered tokens that are lead-in context | {context / total:.1%} |",
        f"| Queries with a skipped hit | {sum(1 for q in report.queries if q.skipped)} "
        f"of {len(report.queries)} |",
        f"| Tokens handed over for the {len(negatives)} negatives, mean | "
        f"{sum(q.tokens for q in negatives) / max(len(negatives), 1):.0f} |",
        "",
        "## Queries whose coverage changed",
        "",
        "| query | slice | ranking | pack | delivered units | question |",
        "|---|---|---|---|---|---|",
        *[
            f"| {q.query_id} | {q.slice.value} | {before[q.query_id]:.2f} "
            f"| {after[q.query_id]:.2f} | {', '.join(q.units)} | {q.question} |"
            for q in (*gains, *losses)
        ],
        *([] if gains or losses else ["| — | | | | | |"]),
        "",
        "## Skipped hits",
        "",
        "Hits in the pool whose full text did not fit.",
        "",
        "| query | skipped | question |",
        "|---|---|---|",
        *[
            f"| {q.query_id} | {', '.join(q.skipped)} | {q.question} |"
            for q in report.queries
            if q.skipped
        ],
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    configure_logging()
    settings = Settings()
    started = time.perf_counter()
    store = settings.vectors_dir / VECTORS_KEY

    corpus_version = read_corpus_version(settings.interim_dir / "corpus_manifest.json")
    try:
        chunks, _ = load_chunks(settings.interim_dir, corpus_version=corpus_version)
        embedder = JinaAPIEmbedder.from_settings(settings)
    except (RuntimeError, MissingSettingError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    gold = load_gold_set(settings.evals_dir / "datasets" / GOLD_V2_FILENAME)
    with embedder:
        try:
            dense = DenseRetriever.from_store(
                store, chunks, embedder, corpus_version=corpus_version
            )
            cached = load_query_vectors(
                store / QUERY_VECTORS_FILENAME,
                model=embedder.info(),
                questions=[q.question for q in gold],
            )
        except (RuntimeError, DenseRetrievalError, StaleVectorStoreError) as error:
            print(f"error: {error} (run scripts/measure_hybrid.py first)", file=sys.stderr)
            return 1

    index = CitationIndex(chunks)
    hybrid = ShortcutRetriever(
        CitationRetriever(chunks),
        FusionRetriever([CachedQueryRetriever(dense, cached.vectors), BM25Retriever(chunks)]),
    )
    packer = EvidencePacker(chunks)

    ranked = measure("hybrid+citation_shortcut", hybrid, gold, index, ordinal_scores=True)
    queries, runs, samples = [], {}, []
    for query in gold:
        results = hybrid.search(query.question, EVIDENCE_POOL)
        began = time.perf_counter()
        pack = packer.pack(results)
        samples.append((time.perf_counter() - began) * 1000)
        runs[query.query_id] = [unit.citation for unit in pack.units]
        queries.append(
            QueryDelivery(
                query_id=query.query_id,
                slice=query.slice,
                question=query.question,
                units=tuple(runs[query.query_id]),
                tokens=pack.tokens,
                context_tokens=context_tokens(pack),
                skipped=pack.skipped,
            )
        )
    delivered = score_run(gold, runs, EVIDENCE_POOL, index)

    report = EvidenceReport(
        corpus_version=corpus_version,
        chunk_count=len(chunks),
        gold_count=len(gold),
        budget=EVIDENCE_BUDGET,
        pool=EVIDENCE_POOL,
        ranked_k=PRIMARY_K,
        ranked=ranked.primary,
        delivered=delivered,
        verdict=judge_delivery(delivered, ranked.primary),
        queries=tuple(queries),
        pack_ms=percentiles(samples),
    )

    artifact_dir = settings.evals_dir / "reports" / corpus_version
    artifact_dir.mkdir(parents=True, exist_ok=True)
    artifact = artifact_dir / ARTIFACT
    with artifact.open("w", encoding="utf-8", newline="") as handle:
        handle.write(
            json.dumps(
                report.model_dump(mode="json"),
                sort_keys=True,
                ensure_ascii=False,
                separators=(",", ":"),
            )
        )
        handle.write("\n")

    elapsed = time.perf_counter() - started
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(render(report, elapsed), encoding="utf-8", newline="")

    for label, run in (("ranking top 10", ranked.primary), ("delivered pack", delivered)):
        overall = run.overall[CreditMode.LENIENT]
        print(f"{label}: lenient recall {overall.recall:.3f}")
    verdict = report.verdict
    print(f"verdict: {'ADOPTED' if verdict.adopted else 'REJECTED'} {list(verdict.reasons)}")
    print(f"wrote {artifact}")
    print(f"wrote {REPORT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
