"""Steps 5.4/5.5 — cross-reference expansion measured against the Step 5.3 pack
it extends, judged by the rule registered in `taxverity.evals.delivery` before
this script first ran (ADR-083).

Both packs are built from the same hybrid + shortcut ranking at the same budget,
so the only difference is the referenced units. Reads the cached gold-question
vectors Step 5.2 wrote, so it bills no tokens. Requires `TAXVERITY_JINA_API_KEY`
all the same: the embedder's identity is checked against the vector store.

Writes `evals/reports/<corpus_version>/xref_expansion.json` and
`reports/xref_expansion.md`.
"""

from __future__ import annotations

import json
import math
import sys
import time
from collections.abc import Sequence
from pathlib import Path

from pydantic import BaseModel, ConfigDict

from taxverity.chunking.pipeline import read_corpus_version
from taxverity.chunking.store import load_chunks
from taxverity.config import MissingSettingError, Settings
from taxverity.embedding.jina_api import JinaAPIEmbedder
from taxverity.embedding.store import StaleVectorStoreError
from taxverity.evals.delivery import judge_expansion
from taxverity.evals.gold import GOLD_V2_FILENAME, QuerySlice, load_gold_set
from taxverity.evals.ladder import Verdict
from taxverity.evals.metrics import CitationIndex, CreditMode, RunReport, score_run
from taxverity.evals.query_vectors import (
    QUERY_VECTORS_FILENAME,
    CachedQueryRetriever,
    load_query_vectors,
)
from taxverity.observability import configure_logging, get_logger
from taxverity.retrieval.bm25 import BM25Retriever
from taxverity.retrieval.citations import CitationRetriever, ShortcutRetriever
from taxverity.retrieval.dense import DenseRetrievalError, DenseRetriever
from taxverity.retrieval.evidence import (
    EVIDENCE_BUDGET,
    EVIDENCE_POOL,
    EXPANSION_HEAD,
    EvidencePack,
    EvidencePacker,
    EvidenceRole,
)
from taxverity.retrieval.fusion import FusionRetriever

logger = get_logger(__name__)

REPORT = Path("reports") / "xref_expansion.md"
ARTIFACT = "xref_expansion.json"
VECTORS_KEY = "jina-api"


class QueryExpansion(BaseModel):
    model_config = ConfigDict(frozen=True)

    query_id: str
    slice: QuerySlice
    question: str
    packed: tuple[str, ...]
    expanded: tuple[str, ...]
    # "target <- citer" for every referenced unit, in pack order.
    referenced: tuple[str, ...]
    packed_tokens: int
    expanded_tokens: int
    referenced_tokens: int


class XrefReport(BaseModel):
    model_config = ConfigDict(frozen=True)

    corpus_version: str
    chunk_count: int
    gold_count: int
    budget: int
    pool: int
    head: int
    packed: RunReport
    expanded: RunReport
    verdict: Verdict
    queries: tuple[QueryExpansion, ...]
    pack_ms: tuple[float, float]


def percentiles(samples: Sequence[float]) -> tuple[float, float]:
    ordered = sorted(samples)
    return ordered[len(ordered) // 2], ordered[math.ceil(0.95 * len(ordered)) - 1]


def referenced_units(pack: EvidencePack):
    return [unit for unit in pack.units if unit.role is EvidenceRole.REFERENCED]


def lenient(report: RunReport) -> dict[str, float]:
    return {s.query_id: s.lenient.recall for s in report.scored}


def render(report: XrefReport, elapsed: float) -> str:
    answerable = [q for q in report.queries if q.slice is not QuerySlice.NEGATIVE]
    negatives = [q for q in report.queries if q.slice is QuerySlice.NEGATIVE]
    before, after = lenient(report.packed), lenient(report.expanded)
    gains = [q for q in answerable if after[q.query_id] > before[q.query_id]]
    losses = [q for q in answerable if after[q.query_id] < before[q.query_id]]
    total = sum(q.expanded_tokens for q in report.queries)
    referenced = sum(q.referenced_tokens for q in report.queries)
    tokens = sorted(q.expanded_tokens for q in answerable)
    verdict = report.verdict
    lines = [
        "# Cross-reference expansion — Income-tax Act, 2025",
        "",
        "Auto-generated by `scripts/measure_xref.py` (Steps 5.4/5.5). The Step 5.3",
        "pack against the same pack with one-hop references added (ADR-083): hits",
        f"ranked 1-{report.head} first, then what those units refer to, then the rest",
        "of the pool, in one budget. Token counts are the Step 2.3 proxy.",
        "",
        "| Measure | Value |",
        "|---|---|",
        f"| corpus_version | `{report.corpus_version[:16]}…` |",
        f"| Chunks | {report.chunk_count} |",
        f"| Gold queries | {report.gold_count} |",
        f"| Budget / pool / head | {report.budget} tokens / top {report.pool} "
        f"/ top {report.head} |",
        f"| Expanded pack time p50 / p95 | {report.pack_ms[0]:.2f} "
        f"/ {report.pack_ms[1]:.2f} ms |",
        f"| Run time | {elapsed:.1f}s |",
        "",
        "## The rule (registered before the run, ADR-083)",
        "",
        "Against the Step 5.3 pack: the crossref slice's lenient recall must rise,",
        "and neither the overall figure nor any slice may fall.",
        "",
        f"**Verdict: {'ADOPTED' if verdict.adopted else 'REJECTED'}.**",
        "",
        *([f"- {reason}" for reason in verdict.reasons] or ["- every clause held"]),
        "",
        "## Coverage",
        "",
        "Lenient recall: the share of labels whose text the evidence carries.",
        "",
        "| slice | Step 5.3 pack | expanded pack |",
        "|---|---|---|",
        f"| overall | {report.packed.overall[CreditMode.LENIENT].recall:.3f} "
        f"| {report.expanded.overall[CreditMode.LENIENT].recall:.3f} |",
    ]
    for member, scores in report.packed.per_slice.items():
        lines.append(
            f"| {member.value} | {scores[CreditMode.LENIENT].recall:.3f} "
            f"| {report.expanded.per_slice[member][CreditMode.LENIENT].recall:.3f} |"
        )
    lines += [
        "",
        "## Cost",
        "",
        "| Measure | Value |",
        "|---|---|",
        f"| Tokens per answerable expanded pack, p50 / p95 / max | {tokens[len(tokens) // 2]} "
        f"/ {tokens[math.ceil(0.95 * len(tokens)) - 1]} / {tokens[-1]} |",
        f"| Referenced units per answerable pack, mean | "
        f"{sum(len(q.referenced) for q in answerable) / len(answerable):.2f} |",
        f"| Share of delivered tokens that are referenced units | {referenced / total:.1%} |",
        f"| Queries with at least one referenced unit | "
        f"{sum(1 for q in report.queries if q.referenced)} of {len(report.queries)} |",
        f"| Referenced tokens handed to the {len(negatives)} negatives, mean | "
        f"{sum(q.referenced_tokens for q in negatives) / max(len(negatives), 1):.0f} |",
        "",
        "## Queries whose coverage changed",
        "",
        "| query | slice | 5.3 pack | expanded | referenced (target ← citer) | question |",
        "|---|---|---|---|---|---|",
        *[
            f"| {q.query_id} | {q.slice.value} | {before[q.query_id]:.2f} "
            f"| {after[q.query_id]:.2f} | {', '.join(q.referenced) or '—'} | {q.question} |"
            for q in (*gains, *losses)
        ],
        *([] if gains or losses else ["| — | | | | | |"]),
        "",
        "## Crossref queries still not fully covered",
        "",
        "| query | expanded | expanded pack | question |",
        "|---|---|---|---|",
        *[
            f"| {q.query_id} | {after[q.query_id]:.2f} | {', '.join(q.expanded)} "
            f"| {q.question} |"
            for q in answerable
            if q.slice is QuerySlice.CROSSREF and after[q.query_id] < 1
        ],
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    configure_logging()
    settings = Settings()
    started = time.perf_counter()
    store = settings.vectors_dir / VECTORS_KEY

    corpus_version = read_corpus_version(settings.interim_dir / "corpus_manifest.json")
    try:
        chunks, _ = load_chunks(settings.interim_dir, corpus_version=corpus_version)
        embedder = JinaAPIEmbedder.from_settings(settings)
    except (RuntimeError, MissingSettingError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    gold = load_gold_set(settings.evals_dir / "datasets" / GOLD_V2_FILENAME)
    with embedder:
        try:
            dense = DenseRetriever.from_store(
                store, chunks, embedder, corpus_version=corpus_version
            )
            cached = load_query_vectors(
                store / QUERY_VECTORS_FILENAME,
                model=embedder.info(),
                questions=[q.question for q in gold],
            )
        except (RuntimeError, DenseRetrievalError, StaleVectorStoreError) as error:
            print(f"error: {error} (run scripts/measure_hybrid.py first)", file=sys.stderr)
            return 1

    index = CitationIndex(chunks)
    hybrid = ShortcutRetriever(
        CitationRetriever(chunks),
        FusionRetriever([CachedQueryRetriever(dense, cached.vectors), BM25Retriever(chunks)]),
    )
    packer = EvidencePacker(chunks)

    queries, packed_runs, expanded_runs, samples = [], {}, {}, []
    for query in gold:
        results = hybrid.search(query.question, EVIDENCE_POOL)
        packed = packer.pack(results, expand=False)
        began = time.perf_counter()
        expanded = packer.pack(results, expand=True)
        samples.append((time.perf_counter() - began) * 1000)
        packed_runs[query.query_id] = [unit.citation for unit in packed.units]
        expanded_runs[query.query_id] = [unit.citation for unit in expanded.units]
        extra = referenced_units(expanded)
        queries.append(
            QueryExpansion(
                query_id=query.query_id,
                slice=query.slice,
                question=query.question,
                packed=tuple(packed_runs[query.query_id]),
                expanded=tuple(expanded_runs[query.query_id]),
                referenced=tuple(f"{unit.citation} ← {unit.cited_by}" for unit in extra),
                packed_tokens=packed.tokens,
                expanded_tokens=expanded.tokens,
                referenced_tokens=sum(unit.tokens for unit in extra),
            )
        )
    packed_report = score_run(gold, packed_runs, EVIDENCE_POOL, index)
    expanded_report = score_run(gold, expanded_runs, EVIDENCE_POOL, index)

    report = XrefReport(
        corpus_version=corpus_version,
        chunk_count=len(chunks),
        gold_count=len(gold),
        budget=EVIDENCE_BUDGET,
        pool=EVIDENCE_POOL,
        head=EXPANSION_HEAD,
        packed=packed_report,
        expanded=expanded_report,
        verdict=judge_expansion(expanded_report, packed_report),
        queries=tuple(queries),
        pack_ms=percentiles(samples),
    )

    artifact_dir = settings.evals_dir / "reports" / corpus_version
    artifact_dir.mkdir(parents=True, exist_ok=True)
    artifact = artifact_dir / ARTIFACT
    with artifact.open("w", encoding="utf-8", newline="") as handle:
        handle.write(
            json.dumps(
                report.model_dump(mode="json"),
                sort_keys=True,
                ensure_ascii=False,
                separators=(",", ":"),
            )
        )
        handle.write("\n")

    elapsed = time.perf_counter() - started
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(render(report, elapsed), encoding="utf-8", newline="")

    for label, run in (("step 5.3 pack", packed_report), ("expanded pack", expanded_report)):
        overall = run.overall[CreditMode.LENIENT].recall
        crossref = run.per_slice[QuerySlice.CROSSREF][CreditMode.LENIENT].recall
        print(f"{label}: lenient recall {overall:.3f}, crossref {crossref:.3f}")
    verdict = report.verdict
    print(f"verdict: {'ADOPTED' if verdict.adopted else 'REJECTED'} {list(verdict.reasons)}")
    print(f"wrote {artifact}")
    print(f"wrote {REPORT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
