"""Step 1.5 — parse sections, titles and chapters, and report what is left over."""

from __future__ import annotations

import sys
import time
from collections import Counter
from pathlib import Path

from taxverity.config import Settings
from taxverity.corpus.loader import read_pages_jsonl
from taxverity.corpus.sections import FIRST_SCHEDULE_PAGE, ParsedAct, parse

REPORT = Path("reports") / "section_parse.md"


def sort_key(marker: str) -> tuple[int, str]:
    digits = "".join(c for c in marker if c.isdigit())
    return int(digits), marker[len(digits) :]


def table(rows: list[tuple[str, object]]) -> str:
    body = "\n".join(f"| {name} | {value} |" for name, value in rows)
    return f"| Measure | Value |\n|---|---|\n{body}\n"


def render(act: ParsedAct, elapsed: float) -> str:
    ordered = [sort_key(m) for m in act.markers]
    suffixed = [m for m in act.markers if not m.isdigit()]
    ascending = all(a < b for a, b in zip(ordered, ordered[1:], strict=False))
    footnote_pages = sorted({f.page for f in act.footnotes})
    empty = [n.marker for n in act.sections if not n.text.strip()]

    lines = [
        "# Section parse — Income-tax Act, 2025",
        "",
        "Auto-generated by `scripts/parse_sections.py` (Step 1.5) from",
        "`data/interim/pages.jsonl`. Sections, titles and chapters only —",
        "sub-structure is Step 1.6.",
        "",
        "## Coverage",
        "",
        table(
            [
                ("Pages parsed", f"0–{FIRST_SCHEDULE_PAGE - 1}"),
                ("Sections parsed", len(act.sections)),
                ("Distinct markers", len(set(act.markers))),
                ("Numbering gaps", act.gaps() or "none"),
                ("Strictly ascending", ascending),
                ("Letter-suffixed", ", ".join(suffixed) or "none"),
                ("Sections without a title", sum(1 for n in act.sections if not n.title)),
                ("Sections with empty text", ", ".join(empty) or "none"),
                ("Chapters", len(act.chapters)),
                ("Chapters without a title", sum(1 for c in act.chapters if not c.title)),
                ("Division headings", len(act.divisions)),
                ("Footnote lines separated", len(act.footnotes)),
                ("Pages carrying footnotes", len(footnote_pages)),
                ("Front-matter lines", len(act.front_matter)),
                ("Non-furniture lines", act.body_lines),
                ("Lines attributed", act.attributed_lines()),
                ("**Orphan lines**", f"**{act.body_lines - act.attributed_lines()}**"),
                ("Parse time", f"{elapsed:.1f}s"),
            ]
        ),
        "",
        "## Chapters",
        "",
        "| Numeral | Page | Sections | Title |",
        "|---|---|---|---|",
    ]

    per_chapter = Counter(n.chapter for n in act.sections)
    for chapter in act.chapters:
        lines.append(
            f"| {chapter.numeral} | {chapter.page} | "
            f"{per_chapter.get(chapter.numeral, 0)} | {chapter.title or '—'} |"
        )

    lines += [
        "",
        "## Front matter",
        "",
        "Lines before section 1 — the long title and enacting formula.",
        "",
        "```",
        *[line.content for line in act.front_matter],
        "```",
        "",
        "## Amendment footnotes",
        "",
        "The Act is printed with an amendment apparatus at the foot of the page:",
        "a numbered note (`3. Sub. by Act No. 4 of 2026, w.e.f. 1-4-2026.`)",
        "followed by the **prior, repealed wording** in full. That text is",
        "statutory prose in the same font and size as live law, so leaving it in a",
        "section body would let the Phase 10 verifier quote repealed law and pass",
        "its own citation check. It is separated here and kept verbatim, never",
        "deleted.",
        "",
        f"Detected on {len(footnote_pages)} pages, {len(act.footnotes)} lines total.",
        "",
        "**Known residue** — reported rather than hidden:",
        "",
        "- Page 464 carries a *prospective* amendment note "
        "(`Following clause (b) shall be inserted ... by the Finance Act ...`)",
        "  inline in the body rather than as a numbered foot-of-page note. It is",
        "  not detected and stays in section 393's text.",
        "- Page 0 carries an asterisk note (`*Assented by the President of India on",
        "  21-8-2025.`), which is not numbered and stays in section 1's text.",
        "",
        "## Sample sections",
        "",
        "| Marker | Chapter | Pages | Title |",
        "|---|---|---|---|",
    ]

    for node in act.sections[:5] + act.sections[-3:]:
        pages = f"{node.pages[0]}–{node.pages[-1]}" if node.pages else "—"
        lines.append(
            f"| {node.marker} | {node.chapter} | {pages} | {node.title or '—'} |"
        )

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    settings = Settings()
    source = settings.interim_dir / "pages.jsonl"
    if not source.exists():
        print(f"missing {source} — run scripts/extract_corpus.py first")
        return 1

    started = time.perf_counter()
    act = parse(read_pages_jsonl(source))
    elapsed = time.perf_counter() - started

    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(render(act, elapsed), encoding="utf-8", newline="\n")

    print(f"sections   {len(act.sections)}")
    print(f"chapters   {len(act.chapters)}")
    print(f"footnotes  {len(act.footnotes)} lines")
    print(f"gaps       {act.gaps() or 'none'}")
    print(f"report     {REPORT} ({elapsed:.1f}s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
