"""Step 1.7, Part B — parse the 16 Schedules into StatutoryNode trees.

Reuses substructure.build() for everything below a paragraph; only the
paragraph-boundary scan itself (Schedule/Part headings, paragraph numbering,
footnote-apparatus separation) is new, in taxverity.corpus.schedules.
"""

from __future__ import annotations

import sys
import time
from collections import Counter
from pathlib import Path

from taxverity.config import Settings
from taxverity.corpus.loader import read_pages_jsonl
from taxverity.corpus.models import PageArtifact
from taxverity.corpus.nodes import CITATION_DEPTH_TYPES, NodeType
from taxverity.corpus.schedules import (
    FIRST_SCHEDULE_PAGE,
    ParsedSchedules,
    parse_schedules,
)
from taxverity.corpus.substructure import AnomalyReason
from taxverity.corpus.tables import find_table_regions

REPORT = Path("reports") / "schedule_parse.md"

LADDER = CITATION_DEPTH_TYPES[NodeType.SCHEDULE]


def table(rows: list[tuple[str, object]]) -> str:
    body = "\n".join(f"| {name} | {value} |" for name, value in rows)
    return f"| Measure | Value |\n|---|---|\n{body}\n"


def render(parsed: ParsedSchedules, elapsed: float, region_count: int) -> str:
    nodes = [node for schedule in parsed.schedules for node in schedule.walk()]
    depths = Counter(node.path.depth for node in nodes if node.path)
    by_marker = Counter(anomaly.section for anomaly in parsed.anomalies)

    lines = [
        "# Schedule parse — Income-tax Act, 2025",
        "",
        "Auto-generated by `scripts/parse_schedules.py` (Step 1.7, Part B) from",
        "`data/interim/pages.jsonl`. Parses the 16 Schedules (pages 622-665)",
        "into `StatutoryNode` trees rooted at `NodeType.SCHEDULE`, with",
        "`SCHEDULE_PARAGRAPH` children grown by the same `substructure.build()`",
        "used for sections.",
        "",
        "## Coverage",
        "",
        table(
            [
                ("Schedules", len(parsed.schedules)),
                ("Nodes total", len(nodes)),
                ("— schedule_paragraph", sum(1 for n in nodes if n.type is NodeType.SCHEDULE_PARAGRAPH)),
                *[
                    (f"— {t.value}", sum(1 for n in nodes if n.type is t))
                    for t in LADDER[1:]
                ],
                ("Deepest citation", max(depths)),
                ("Anomalies", len(parsed.anomalies)),
                ("Paragraphs carrying an anomaly", len(parsed.unreliable)),
                ("Footnote apparatus lines", len(parsed.footnotes)),
                ("Schedule/Part headings kept verbatim", len(parsed.headings)),
                ("Table regions measured by pdfplumber", region_count),
                ("Parse time (incl. pdfplumber scan)", f"{elapsed:.1f}s"),
            ]
        ),
        "",
        "## Two typographic families, one boundary rule",
        "",
        "Schedules split into 7 **prose** Schedules (I, IX, X, XI, XIV, XV, XVI)",
        "whose paragraph-opening lines are bold, exactly like sections, and 9",
        "**list** Schedules (II-VIII, XII, XIII) whose row markers are plain",
        "text — they are enumerated table rows, not prose paragraphs. This",
        "overturns an earlier note that Schedule paragraph numbers are not",
        "bold: true for some, false for others, and the difference matters.",
        "",
        "Boldness therefore cannot be the (only) opening cue. What generalises",
        "across both families instead: a candidate line at the Act's left text",
        "margin (measured 27.6-46.4pt), sized >=8pt (excluding the 7.07pt",
        "footnote-reference call-out digits scattered through Schedule pages —",
        "measured exactly, the same discriminator Step 1.5 found for sections),",
        "whose leading number is a plausible next paragraph in the current",
        "Schedule or Part.",
        "",
        "## Numbering is not always exactly contiguous",
        "",
        "Unlike section numbering (536+354A, zero real gaps), Schedule XII Part",
        "A genuinely omits 28 — confirmed by direct search of the text, not a",
        "parsing artefact. The boundary rule tolerates a gap of one, never an",
        "arbitrary jump: a wrapped body line that happens to start a fresh line",
        "with a digit (Schedule XV's \"20 or 21),\" continuation, x0=55.2) is",
        "rejected by the same left-margin cutoff that saves it from being read",
        "as paragraph 20.",
        "",
        "## Parts reset numbering; the Part letter is folded into the marker",
        "",
        "PART sub-headings (Schedule XI: A/B/C; Schedule XII: A/B) reset",
        "paragraph numbering to 1, and share the SCHEDULE heading's bold caption",
        "font. Because numbering restarts per Part, a bare paragraph number is",
        "not a unique citation within its Schedule — \"Schedule XI(1)\" would",
        "otherwise exist three times over. The Part letter is folded into the",
        "node's own marker (`A1`, `B1`, `C1`) to keep citations unique and",
        "round-trippable; parsing the Act's own citation string (\"Part A of",
        "Schedule XI, paragraph 8\") into this form is left to the",
        "not-yet-started cross-reference step.",
        "",
        "## Footnote apparatus continues across the Schedule pages",
        "",
        "The same running amendment-footnote counter that spans the main Act's",
        f"537 footnotes continues here — {len(parsed.footnotes)} more lines,",
        "reusing `sections.footnote_start` unchanged. Giving it an honest",
        "`starts` dict (the genuine Schedule/Part/paragraph boundaries found on",
        "each page) is load-bearing: an early version of this parser passed an",
        "empty dict, and `footnote_start`'s own \"still inside the apparatus\"",
        "continuation shortcut — which fires on any page merely *mentioning*",
        "amendment vocabulary once triggered — swallowed the whole of Schedule",
        "XII as a result. `scan_boundaries` is a side-effect-free replay of the",
        "same rules the real pass applies, run first purely to answer that.",
        "",
        "## depth_shift: a section-only inference, not a Schedule one",
        "",
        "`is_clause_rooted`'s shift exists to skip a SUBSECTION level a",
        "clause-rooted section has no use for (section 2 has no `(1)` before",
        "its `(a)`). A Schedule paragraph's ladder never had that level to",
        "begin with — it starts at CLAUSE directly. Applying the same shift",
        "there mistyped every clause-rooted paragraph's first level as",
        "SUBCLAUSE (found and fixed during this step: Schedule I paragraph 2's",
        "`(a)`-`(e)` list). `build()` now takes an explicit `depth_shift`",
        "override; `schedules.py` always passes `0`.",
        "",
        "## Residue — reported, not hidden",
        "",
        f"{len(parsed.anomalies)} markers could not be placed or produced a",
        f"citation already used, across {len(parsed.unreliable)} paragraphs —",
        "the same residue discipline `substructure.py` already carries for",
        "sections. No text is lost either way: an unplaceable marker's line",
        "stays with its enclosing node.",
        "",
        "| Paragraph | Anomalies |",
        "|---|---|",
    ]

    for marker, count in by_marker.most_common():
        lines.append(f"| {marker} | {count} |")

    lines += [
        "",
        "## Sample tree — Schedule I",
        "",
        "```",
    ]

    sample = parsed.schedule("I")
    if sample is not None:
        for node in sample.walk():
            indent = "  " * max(node.path.depth - 1, 0)
            head = node.text.split("\n")[0] if node.text else (node.title or "")
            lines.append(f"{indent}{node.path.render():<24} {head[:70]}")
    lines += ["```", ""]
    return "\n".join(lines)


def main() -> int:
    settings = Settings()
    source = settings.interim_dir / "pages.jsonl"
    if not source.exists():
        print(f"missing {source} — run scripts/extract_corpus.py first")
        return 1

    started = time.perf_counter()
    pages: list[PageArtifact] = list(read_pages_jsonl(source))
    regions = find_table_regions(
        settings.resolve_corpus_pdf(), range(FIRST_SCHEDULE_PAGE, len(pages))
    )
    parsed = parse_schedules(pages, table_regions=regions)
    elapsed = time.perf_counter() - started

    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(render(parsed, elapsed, len(regions)), encoding="utf-8", newline="\n")

    nodes = sum(1 for schedule in parsed.schedules for _ in schedule.walk())
    print(f"schedules   {len(parsed.schedules)}")
    print(f"nodes       {nodes}")
    for t in LADDER[1:]:
        print(f"  {t.value:<18}{sum(1 for s in parsed.schedules for n in s.walk() if n.type is t)}")
    print(f"table geo   {len(regions)} regions measured by pdfplumber")
    print(f"footnotes   {len(parsed.footnotes)}")
    print(f"anomalies   {len(parsed.anomalies)} in {len(parsed.unreliable)} paragraphs")
    for reason in AnomalyReason:
        print(
            f"  {reason.value:<16}"
            f"{sum(1 for a in parsed.anomalies if a.reason is reason)}"
        )
    print(f"report      {REPORT} ({elapsed:.1f}s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
