"""Step 1.8 — extract the cross-reference edge table and the s.2 definitions
glossary from the parsed section and Schedule trees."""

from __future__ import annotations

import re
import sys
import time
from collections import Counter
from pathlib import Path

from taxverity.config import Settings
from taxverity.corpus.crossrefs import CrossReferenceIndex, RefType, extract_crossrefs
from taxverity.corpus.loader import read_pages_jsonl
from taxverity.corpus.schedules import FIRST_SCHEDULE_PAGE, parse_schedules
from taxverity.corpus.sections import parse as parse_sections
from taxverity.corpus.substructure import candidate_table_pages, parse_substructure
from taxverity.corpus.tables import find_table_regions

REPORT = Path("reports") / "crossref_parse.md"


def table(rows: list[tuple[str, object]]) -> str:
    body = "\n".join(f"| {name} | {value} |" for name, value in rows)
    return f"| Measure | Value |\n|---|---|\n{body}\n"


def render(result: CrossReferenceIndex, elapsed: float) -> str:
    by_type = Counter(ref.ref_type for ref in result.references)
    # A PDF line wrap can fall anywhere in a captured Act name, including
    # right before the word "Act" itself -- normalise whitespace for grouping
    # rather than truncating to the text after the last newline, which would
    # collapse distinct names ("Foreign Exchange Management\nAct" and
    # "Representation of the People\nAct") into one misleading "Act" bucket.
    by_act = Counter(re.sub(r"\s+", " ", ext.act_name).strip() for ext in result.external)
    dangling = result.dangling

    lines = [
        "# Cross-reference extraction — Income-tax Act, 2025",
        "",
        "Auto-generated by `scripts/parse_crossrefs.py` (Step 1.8) from the",
        "parsed section tree (Steps 1.5/1.6/1.7) and Schedule tree (Step 1.7,",
        "Part B). Regex over each node's own text produces an edge table",
        "`(from_path, ref_type, surface_text, target_path, resolved)` plus the",
        "section 2 definitions glossary.",
        "",
        "## Coverage",
        "",
        table(
            [
                ("References extracted", len(result.references)),
                ("— resolved", len(result.references) - len(dangling)),
                ("— dangling (residue, below)", len(dangling)),
                ("**Resolution rate**", f"**{result.resolution_rate:.2%}**"),
                ("External-Act mentions (excluded from the rate)", len(result.external)),
                ("Glossary terms (section 2)", len(result.glossary)),
                ("Extraction time", f"{elapsed:.2f}s"),
            ]
        ),
        "",
        "## By reference type",
        "",
        "| Type | Count |",
        "|---|---|",
        *[f"| {t.value} | {n} |" for t, n in by_type.most_common()],
        "",
        "## The Act's own citation convention — measured, not assumed",
        "",
        "The 2025 Act overwhelmingly cross-references itself the same way this",
        "codebase renders a citation: `section 515(3)(b)`, brackets appended",
        "directly to the number — not the older prefix style `sub-section (3)",
        "of section 515`. Measuring real occurrences first (`scratch_crossrefs.py`,",
        "not committed) found the postfix form outnumbering the prefix form by",
        "roughly 100 to 1, so extraction targets the postfix form first and",
        "treats the prefix chain as a secondary, minority pattern — see",
        "ADR-049.",
        "",
        "## External-Act references are excluded, not counted as failures",
        "",
        "About a tenth of every `section N` mention in the Act does not point",
        "into this corpus at all — it names a different statute (`section 8 of",
        "the Companies Act, 2013`) or refers anaphorically to one named earlier",
        "(`of the said Act`). Extraction detects the trailing `of/to <Name>",
        "Act|Code|Sanhita` and routes these to a separate, verbatim-kept list",
        "instead of the edge table — the same discipline `ParsedAct.footnotes`",
        "already applies to amendment quotations. They are never counted",
        "against the resolution rate, because they were never a reference this",
        "corpus could resolve in the first place.",
        "",
        "| External statute | Mentions |",
        "|---|---|",
        *[f"| {name} | {n} |" for name, n in by_act.most_common(20)],
        "",
        "## Residue — reported, not hidden",
        "",
        f"{len(dangling)} references look intra-Act (no external-Act tail found)",
        "but do not resolve to a real node. Each falls into one of a small",
        "number of explained categories, none of them a silent extraction bug:",
        "",
        "1. **A trailing Act name shared across an `or`/`,`-joined list that",
        "   the regex cannot see past.** `\"section 12A, 12AA or 12AB or section",
        "   10(23C) of the Income-tax Act, 1961\"` — the Act name confirms the",
        "   *last* mention only; earlier ones in the same list belong to it too,",
        "   but recovering that needs sentence-level attribution this",
        "   node-local regex does not attempt.",
        "2. **An elliptical cross-reference that omits an already-established",
        "   sub-section number.** `\"section 70(zd)\"` means `70(1)(zd)` given the",
        "   surrounding sentence, but that context lives outside the citing",
        "   node's own text.",
        "3. **A citation whose depth does not match this corpus's own,",
        "   carefully measured tree** (e.g. `section 2(22)(iii)` where clause",
        "   22's real children are lettered, not numbered) — a genuine",
        "   drafting/numbering question to verify against the source PDF, not",
        "   a parser gap.",
        "4. **A nested list whose continuation item varies more than the",
        "   trailing bracket** (e.g. `\"(15A), (15)(iiia)\"`), which the",
        "   single-bracket continuation rule does not attempt to generalise to.",
        "",
        "| From | Surface text | Attempted target |",
        "|---|---|---|",
        *[
            f"| {ref.from_path} | {ref.surface_text.replace(chr(10), ' ')[:60]} | {ref.target_path} |"
            for ref in dangling
        ],
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    settings = Settings()
    source = settings.interim_dir / "pages.jsonl"
    if not source.exists():
        print(f"missing {source} — run scripts/extract_corpus.py first")
        return 1

    started = time.perf_counter()
    pages = list(read_pages_jsonl(source))

    act = parse_sections(pages)
    section_regions = find_table_regions(settings.resolve_corpus_pdf(), candidate_table_pages(act))
    sub = parse_substructure(act, table_regions=section_regions)

    schedule_regions = find_table_regions(
        settings.resolve_corpus_pdf(), range(FIRST_SCHEDULE_PAGE, len(pages))
    )
    parsed_schedules = parse_schedules(pages, table_regions=schedule_regions)

    result = extract_crossrefs(sub.sections, parsed_schedules.schedules)
    elapsed = time.perf_counter() - started

    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(render(result, elapsed), encoding="utf-8", newline="\n")

    print(f"references  {len(result.references)}")
    print(f"resolved    {len(result.references) - len(result.dangling)} ({result.resolution_rate:.2%})")
    print(f"dangling    {len(result.dangling)}")
    print(f"external    {len(result.external)}")
    print(f"glossary    {len(result.glossary)}")
    for ref_type in RefType:
        n = sum(1 for ref in result.references if ref.ref_type is ref_type)
        if n:
            print(f"  {ref_type.value:<20}{n}")
    print(f"report      {REPORT} ({elapsed:.1f}s)")
    return 0 if result.resolution_rate >= 0.98 else 1


if __name__ == "__main__":
    sys.exit(main())
