"""Step 1.6/1.7 — grow sections into sub-sections, clauses, sub-clauses, items,
and (Step 1.7) bound in-section Tables by measured pdfplumber geometry where
it is reliable."""

from __future__ import annotations

import sys
import time
from collections import Counter
from pathlib import Path

from taxverity.config import Settings
from taxverity.corpus.loader import read_pages_jsonl
from taxverity.corpus.sections import ParsedAct, parse
from taxverity.corpus.substructure import (
    LEVEL_TYPES,
    AnomalyReason,
    Substructure,
    candidate_table_pages,
    parse_substructure,
    round_trip_failures,
)
from taxverity.corpus.tables import find_table_regions
from taxverity.observability import configure_logging, get_logger

logger = get_logger(__name__)

REPORT = Path("reports") / "substructure_parse.md"


def table(rows: list[tuple[str, object]]) -> str:
    body = "\n".join(f"| {name} | {value} |" for name, value in rows)
    return f"| Measure | Value |\n|---|---|\n{body}\n"


def render(
    act: ParsedAct, sub: Substructure, elapsed: float, region_count: int
) -> str:
    nodes = [node for section in sub.sections for node in section.walk()]
    depths = Counter(node.path.depth for node in nodes if node.path)
    by_section = Counter(anomaly.section for anomaly in sub.anomalies)
    off_table = [m for m in by_section if m not in sub.table_sections]
    failures = round_trip_failures(sub.sections, act.sections)

    lines = [
        "# Sub-structure parse — Income-tax Act, 2025",
        "",
        "Auto-generated by `scripts/parse_substructure.py` (Steps 1.6/1.7) from",
        "`data/interim/pages.jsonl`. Sections come from Step 1.5; Step 1.6 grows",
        "each one into its tree of sub-sections, clauses, sub-clauses and items;",
        "Step 1.7 additionally bounds in-section Tables by real pdfplumber table",
        "geometry, on pages where that geometry is measured to be reliable.",
        "",
        "## Coverage",
        "",
        table(
            [
                ("Sections", len(sub.sections)),
                ("Nodes total", len(nodes)),
                ("Nodes below section", len(nodes) - len(sub.sections)),
                *[
                    (f"— {type.value}", sub.count(type))
                    for type in LEVEL_TYPES
                ],
                ("Deepest citation", max(depths)),
                ("Nodes without page provenance", sum(1 for n in nodes if not n.pages)),
                ("**Round-trip failures**", f"**{len(failures)}**"),
                ("Anomalies", len(sub.anomalies)),
                ("Sections carrying an anomaly", len(sub.unreliable)),
                ("Clause-rooted sections", len(sub.clause_rooted)),
                ("Sections carrying a Table", len(sub.table_sections)),
                ("Table regions measured by pdfplumber", region_count),
                ("Parse time (incl. pdfplumber scan)", f"{elapsed:.1f}s"),
            ]
        ),
        "",
        "**Round-trip is the success criterion for this step**: for every section,",
        "`node.full_text()` must reproduce the exact text Step 1.5 handed over.",
        "Nothing is normalised, dropped or reordered — markers stay in the line",
        "they were printed on, so ADR-016's quote-fidelity check still works",
        "against a node's own text.",
        "",
        "## Depth distribution",
        "",
        "Depth counts the citation's components, so a section is 1 and `9(5)(a)` is 3.",
        "",
        "| Depth | Nodes |",
        "|---|---|",
        *[f"| {depth} | {count} |" for depth, count in sorted(depths.items())],
        "",
        "## How a node's type is decided",
        "",
        "Never from the marker's shape. Page 27 runs a clause sequence `a…h, i, j`,",
        "so `(i)` is a sub-clause in one section and a clause in another. Placement",
        "is by **sibling sequence**: a marker that continues an open level closes",
        "everything below it, and a marker that opens an alphabet not already on",
        "the stack pushes a new level.",
        "",
        "Three cases the sequence rule alone cannot settle, each resolved",
        "deterministically and each measured:",
        "",
        "1. **`(h)` → `(i)`** is both the next letter and the first roman numeral.",
        "   The *next* marker decides: `(j)` means sibling, `(ii)` means a nested",
        "   list. Section 19(2)(h) opens `i, ii, iii`; page 27 continues `i, j`.",
        "2. **A repeated alphabet** — `416(5)(g)` really does contain `(a)`, `(b)`.",
        "   A repeat nests only when the line above announces a list by ending in",
        "   `—` or `:`; otherwise it restarts the level already open.",
        "3. **A wrapped cross-reference** at the start of a line is not a node.",
        "   Section 44(1) ends a line on “… specified in sub-section” and the next",
        "   line begins `(2)—`, which would otherwise consume the marker that the",
        "   real sub-section (2) needs. A line-initial marker is refused when the",
        "   line above ends on `section`, `clause`, `item`, `paragraph`, `schedule`",
        "   or `under`. Measured: 23 of 23 false markers caught, 0 of 33 real",
        "   markers lost.",
        "",
        "## Sub-section or clause? — the first level below a section",
        "",
        "The Act calls section 9's `(1)` a **sub-section** and section 2's `(22)` a",
        "**clause**, and the two markers are typographically identical. What",
        "separates them is the section's own opening line: a clause run continues a",
        "sentence the section began (`2. In this Act, unless the context otherwise",
        "requires,—`), whereas a sub-section carries its marker inline (`9. (1) The",
        "income referred to …`). An opening line that is bare means the marker",
        "merely wrapped, so it is a sub-section.",
        "",
        "Validated against the Act's own vocabulary — whether a section ever says",
        "“sub-section (” about itself — **536 of 537 sections agree**. The single",
        "exception, section 428, refers to a *different* section's sub-section.",
        "",
        f"{len(sub.clause_rooted)} sections are clause-rooted. Their levels shift",
        "down one rung, which is why `2(5)(b)(ii)` types as an **item** — and the",
        "Act's own text confirms it, describing that node as “the nature described",
        "in item (ii)”.",
        "",
        "## Residue — reported, not hidden",
        "",
        f"{len(sub.anomalies)} markers could not be placed or produced a citation",
        f"already used, across {len(sub.unreliable)} sections. No text is lost by",
        "either: an unplaceable marker's line stays with its enclosing node, which",
        "is why round-trip still holds. `Substructure.unreliable` names these",
        "sections so a consumer can decline to trust their shape.",
        "",
        "| Section | Anomalies | Carries a Table |",
        "|---|---|---|",
    ]

    for marker, count in by_section.most_common():
        lines.append(
            f"| {marker} | {count} | {'yes' if marker in sub.table_sections else 'no'} |"
        )

    lines += [
        "",
        "### The in-section Table, and what Step 1.7 fixed in it",
        "",
        f"{len(sub.table_sections)} sections print a `TABLE` block inside a"
        " sub-section.",
        "Its cells carry their own `(a)`/`(i)`/`(1)` runs in the same font as live",
        "law. Step 1.6's rule was the only one available then — suppress markers",
        "inside a Table and end the block on whichever one resumes an already-open",
        "sequence — and it was not enough for a **two-column** Table. Section 206",
        "prints columns A and B whose rows both number `(1)…(5)`, and the cell",
        "`(2)` resumes the enclosing sub-section sequence, so the block closed",
        "early and the real sub-section 206(2) had nowhere to go: 56 of 1.6's 96",
        "anomalies, on its own.",
        "",
        "**Step 1.7 measured real table geometry with pdfplumber**, restricted to"
        f" the {region_count} pages already known — from our own `TABLE` line —",
        "to carry one; never a blind scan, which Step 1.1 measured to",
        "false-positive on ordinary prose. A line pdfplumber positively places",
        "inside a ruled grid is now trusted outright, whatever marker it carries,",
        "which is exactly what section 206 needed and fixes it completely.",
        "",
        "That geometry is not uniformly available, and the fix is deliberately",
        "one-directional because of it: a *measured* line only ever adds",
        "suppression; its *absence* never forces the old guess to close early.",
        "pdfplumber's own extraction degenerates to one useless whole-page cell on",
        "several of these pages (sections 2, 194, 46, 52, 394 and most of 393 —",
        "their tables are borderless, with no ruling lines to detect), and even",
        "where it succeeds it can measure only part of a table (section 39's ruled",
        "region covers 6 of its rows; the rest spill onto the next page",
        "unmeasured). Resetting the guess on any of those absences reintroduced",
        "duplicate-path anomalies in sections 1.6 already got right — measured",
        "directly during this step, not guessed — which is why the old heuristic",
        "is left in sole control wherever geometry has nothing positive to add.",
        "",
        f"The {len(off_table)} anomalous sections with no Table"
        f" ({', '.join(sorted(off_table))}) are almost all the opposite case —",
        "a wrapped cross-reference correctly refused, such as section 67's",
        "`(l) of the Depositories Act, 1996 (22 of 1996).`",
        "",
        "The Schedules parser (1.7's other half) is a separate module —",
        "`schedules.py` — with its own boundary rule, since Schedule paragraph",
        "numbers are bold in some Schedules and plain in others (unlike 1.5's",
        "bold+regex cue for sections). See `reports/schedule_parse.md`.",
        "",
        "## Sample tree — section 9(5)",
        "",
        "```",
    ]

    sample = sub.node("9(5)")
    if sample is not None:
        for node in sample.walk():
            indent = "  " * (node.path.depth - 2)
            head = node.text.split("\n")[0] if node.text else ""
            lines.append(f"{indent}{node.path.render():<24} {head[:70]}")
    lines += ["```", ""]
    return "\n".join(lines)


def main() -> int:
    configure_logging()
    settings = Settings()
    source = settings.interim_dir / "pages.jsonl"
    if not source.exists():
        logger.error("missing %s — run scripts/extract_corpus.py first", source)
        return 1

    started = time.perf_counter()
    act = parse(read_pages_jsonl(source))
    regions = find_table_regions(settings.resolve_corpus_pdf(), candidate_table_pages(act))
    sub = parse_substructure(act, table_regions=regions)
    elapsed = time.perf_counter() - started

    failures = round_trip_failures(sub.sections, act.sections)
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(
        render(act, sub, elapsed, len(regions)), encoding="utf-8", newline="\n"
    )

    nodes = sum(1 for section in sub.sections for _ in section.walk())
    print(f"nodes       {nodes} ({nodes - len(sub.sections)} below section level)")
    for type in LEVEL_TYPES:
        print(f"  {type.value:<12}{sub.count(type)}")
    print(f"round-trip  {'OK' if not failures else 'FAILED: ' + ', '.join(failures)}")
    print(f"table geo   {len(regions)} regions measured by pdfplumber")
    print(f"anomalies   {len(sub.anomalies)} in {len(sub.unreliable)} sections")
    for reason in AnomalyReason:
        print(
            f"  {reason.value:<16}"
            f"{sum(1 for a in sub.anomalies if a.reason is reason)}"
        )
    print(f"report      {REPORT} ({elapsed:.1f}s)")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
