"""Step 1.3 driver — probe the extracted artifact for structure and report every gap."""

import sys

from taxverity.config import Settings
from taxverity.corpus.loader import read_pages_jsonl
from taxverity.corpus.probe import probe
from taxverity.observability import configure_logging, get_logger

logger = get_logger(__name__)

EXPECTED_SECTIONS = 536


def render(result) -> str:
    bold = result.numbers_by_cue("bold")
    regex = result.numbers_by_cue("regex")
    found = result.all_numbers
    gaps = result.gaps(EXPECTED_SECTIONS)
    duplicates = result.duplicates()
    first_schedule_page = min((page for _, page in result.schedules), default=None)
    single_cue = sorted(
        (c.number, c.suffix)
        for c in result.candidates
        if len(c.cues) == 1 and c.cues[0] == "regex"
    )
    single_cue = [f"{n}{x}" for n, x in single_cue]
    untitled = sorted(
        (c.number, c.suffix) for c in result.candidates if c.title is None
    )

    out = [
        "# Structure probe — Income-tax Act, 2025",
        "",
        "Auto-generated by `scripts/probe_structure.py` (Step 1.3) from",
        "`data/interim/pages.jsonl`. **The failures are the deliverable here** —",
        "this step exists so the gaps are visible before Step 1.5 tries to close",
        "them.",
        "",
        "## Coverage",
        "",
        "| Measure | Value |",
        "|---|---|",
        f"| Sections expected | {EXPECTED_SECTIONS} |",
        f"| Detected by the bold-span cue | {len(bold)} |",
        f"| Detected by the line-start regex cue | {len(regex)} |",
        f"| **Detected by either cue** | **{len(found)}** |",
        f"| Missing entirely | **{len(gaps)}** |",
        f"| Numbers seen on more than one page | {len(duplicates)} |",
        f"| Letter-suffixed sections (e.g. 354A) | {len(result.suffixed)} |",
        f"| Resting on the weaker regex cue alone | {len(single_cue)} |",
        f"| Detected without a title | {len(untitled)} |",
        "",
        f"- Chapters detected: **{len(result.chapters)}**",
        f"- Schedules detected: **{len(result.schedules)}**",
        "",
        "## Gaps — sections no cue found",
        "",
    ]
    out.append(
        "None. Every section from 1 to "
        f"{EXPECTED_SECTIONS} was located by at least one cue."
        if not gaps
        else "| Section |\n|---|\n" + "\n".join(f"| {n} |" for n in gaps)
    )

    out += [
        "",
        "## Sections resting on the regex cue alone",
        "",
        "These lack a bold `<n>.` span, so they are the weakest detections and the",
        "most likely false positives. Step 1.5 should confirm each one.",
        "",
    ]
    out.append(", ".join(single_cue) if single_cue else "None.")

    out += [
        "",
        "## Letter-suffixed sections",
        "",
        "Only bold-cue hits in the body are real. Regex-only hits at or after the",
        "first Schedule page are references to the Income-tax Act, **1961**, which",
        "the Schedules cite heavily — not sections of this Act.",
        "",
        "| Label | Page | Cues | Reading |",
        "|---|---|---|---|",
    ]
    for candidate in sorted(result.suffixed, key=lambda c: c.page):
        real = "bold" in candidate.cues and (
            first_schedule_page is None or candidate.page < first_schedule_page
        )
        out.append(
            f"| {candidate.label} | {candidate.page} | {'+'.join(candidate.cues)} "
            f"| {'**real section**' if real else 'likely a 1961-Act reference'} |"
        )
    if not result.suffixed:
        out.append("| — | — | — | none |")

    collisions = sum(
        1
        for pages in duplicates.values()
        for page in pages
        if first_schedule_page is not None and page >= first_schedule_page
    )
    out += [
        "",
        "## Numbers appearing on more than one page",
        "",
        "**Not** the arrangement-of-sections listing — that page does not produce",
        "false detections. Every repeat comes from the Schedules, which restart",
        f"numbering at 1 and use identical typography to sections. The first "
        f"Schedule is on page {first_schedule_page}, and {collisions} of the "
        "repeated occurrences fall at or after it.",
        "",
        "**Consequence for Step 1.5:** section parsing must be bounded to the pages",
        "before the first Schedule, or otherwise scoped by container. A bare",
        "`<n>.` cue cannot tell section 1 from Schedule X paragraph 1.",
        "",
        "| Section | Pages |",
        "|---|---|",
    ]
    for number, pages in list(duplicates.items())[:40]:
        shown = ", ".join(str(p) for p in pages[:8])
        more = f" (+{len(pages) - 8})" if len(pages) > 8 else ""
        out.append(f"| {number} | {shown}{more} |")
    if len(duplicates) > 40:
        out.append(f"| … | {len(duplicates) - 40} more |")

    out += ["", "## Chapters", "", "| Numeral | Page |", "|---|---|"]
    out += [f"| {numeral} | {page} |" for numeral, page in result.chapters]

    out += ["", "## Schedules", "", "| Numeral | Page |", "|---|---|"]
    out += [f"| {numeral} | {page} |" for numeral, page in result.schedules]

    out += [
        "",
        "## Detected sections",
        "",
        "First detection of each number, in page order.",
        "",
        "| Section | Page | Cues | Title |",
        "|---|---|---|---|",
    ]
    seen = set()
    for candidate in sorted(
        result.candidates, key=lambda c: (c.number, c.suffix, c.page)
    ):
        if candidate.label in seen:
            continue
        seen.add(candidate.label)
        title = (candidate.title or "—").replace("|", "\\|")[:70]
        out.append(
            f"| {candidate.label} | {candidate.page} | {'+'.join(candidate.cues)} | {title} |"
        )

    return "\n".join(out) + "\n"


def main():
    configure_logging()
    settings = Settings()
    pages_path = settings.interim_dir / "pages.jsonl"
    if not pages_path.is_file():
        raise SystemExit(
            f"{pages_path} not found — run scripts/extract_corpus.py first."
        )

    result = probe(read_pages_jsonl(pages_path))
    settings.reports_dir.mkdir(parents=True, exist_ok=True)
    report_path = settings.reports_dir / "structure_probe.md"
    report_path.write_text(render(result), encoding="utf-8")

    logger.info("wrote %s", report_path)
    print(
        f"  sections {len(result.all_numbers)}/{EXPECTED_SECTIONS}, "
        f"gaps {len(result.gaps(EXPECTED_SECTIONS))}, "
        f"chapters {len(result.chapters)}, schedules {len(result.schedules)}",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
